version: "3.7"

services:
  php:
    build:
      context: .
      target: app_php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"

  caddy:
    image: caddy:2.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./public:/var/www/html/public:ro
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-root}
    ports:
      - "27017:27017"

volumes:
  caddy_data:
  caddy_config:


