# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Shared\Application\Command\CommandHandlerInterface:
            public: true
            tags:
                - { name: messenger.message_handler, bus: command.bus }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Shared\Infrastructure\JWTBuilder:
        arguments:
            - '%env(resolve:JWT_SECRET_KEY)%'

    app.mongodb_client:
        class: MongoDB\Client
        arguments: [ '%env(resolve:MONGODB_URL)%' ]

    app.event_store.mongodb_collection:
        class: MongoDB\Collection
        factory: [ '@app.mongodb_client', selectCollection ]
        arguments: [ '%env(resolve:MONGODB_DB)%', 'events' ]

#    app.event_store.mongodb:
#        class: App\Shared\Infrastructure\EventSourcing\MongoDBEventStore
#        arguments: [ '@app.event_store.mongodb_collection']

    App\Shared\Infrastructure\EventSourcing\MongoDBEventStore:
        arguments:
            - '@app.event_store.mongodb_collection'

    App\Room\Infrastructure\ReadModel\MongoDBReadModelRoomRepository:
        arguments:
            - '@app.mongodb_client'